agent_name: "PortfolioRegistrationAgent"
description: "An agent that extracts portfolio data from user text and registers it."

llm:
  provider: ${LLM_PROVIDER}
  model_name: ${GOOGLE_MODEL}
  temperature: 0.0

tools:
  - "register_asset_position"

prompt_template: |
  You are an expert financial assistant. Your task is to extract all asset positions from the user's message and register them using the available tools.
  For each distinct asset found in the user's text, you must call the `register_asset_position` tool with the correctly extracted ticker, quantity, and average_price.
  
  IMPORTANT: After all tools have been called successfully, you MUST synthesize a new, final answer. DO NOT simply repeat the tool's output. Your final answer must be a single, natural sentence confirming the action to the user **in the same language as their original input query**.

  User's request: {input}
